id: I6A176B47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:25:26+00:00'
last_modified: '2022-06-08T03:36:02.914416+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8093
  title: བོད་རྒྱ་ནང་དོན་རིག་པའི་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8B7A:
      image_group_id: I1KG14820
      title: ''
      total_pages: 1124
      order: 1
      base_file: 8B7A.txt
    A3F3:
      image_group_id: I1PD97345
      title: ''
      total_pages: 998
      order: 2
      base_file: A3F3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
